let state = {
    permissions: [],
    toRemovePermission: null,
    todos: false,
    teamTodos: false,
    toRemoveToDo: null,
    completeTodo: null,
    todoCompletedCount: 0,
    highPrirityCount: 0,
    todoCount: 0,
    completedTodos: [],
    baseCurrency: null,
    currencyValues: [],
    currentCurrency: null,
    newTodo: {
        id: '',
        title: '',
        about: '',
        assigned: [],
        to_do_status_id: 1,
        priority_id: '',
        type: '',
        task_date: ''
    },
    notifications: [],
    notificationCount: 0,
    readNotificatio: null,
    items: [
        {
            id: '',
            item_name: '',
            qty: '',
            unit_price: '',
            tax: 5,
            round_helper: '',
            total: '',
            inventory: [
                {
                    id: '',
                    sku: '',
                    name: '',
                    cost: '',
                    qty: '',
                    margin: '',
                    selling_price: '',
                }
            ]
        }
    ],
    showSidePage: false,
    countryOpt: [
        { id: "", text: "Select Nationality" },
        { id: "AF", text: "Afghanistan" },
        { id: "AX", text: "Aland Islands" },
        { id: "AL", text: "Albania" },
        { id: "DZ", text: "Algeria" },
        { id: "AS", text: "American Samoa" },
        { id: "AD", text: "Andorra" },
        { id: "AO", text: "Angola" },
        { id: "AI", text: "Anguilla" },
        { id: "AQ", text: "Antarctica" },
        { id: "AG", text: "Antigua And Barbuda" },
        { id: "AR", text: "Argentina" },
        { id: "AM", text: "Armenia" },
        { id: "AW", text: "Aruba" },
        { id: "AU", text: "Australia" },
        { id: "AT", text: "Austria" },
        { id: "AZ", text: "Azerbaijan" },
        { id: "BS", text: "Bahamas" },
        { id: "BH", text: "Bahrain" },
        { id: "BD", text: "Bangladesh" },
        { id: "BB", text: "Barbados" },
        { id: "BY", text: "Belarus" },
        { id: "BE", text: "Belgium" },
        { id: "BZ", text: "Belize" },
        { id: "BJ", text: "Benin" },
        { id: "BM", text: "Bermuda" },
        { id: "BT", text: "Bhutan" },
        { id: "BO", text: "Bolivia" },
        { id: "BA", text: "Bosnia And Herzegovina" },
        { id: "BW", text: "Botswana" },
        { id: "BV", text: "Bouvet Island" },
        { id: "BR", text: "Brazil" },
        { id: "IO", text: "British Indian Ocean Territory" },
        { id: "BN", text: "Brunei Darussalam" },
        { id: "BG", text: "Bulgaria" },
        { id: "BF", text: "Burkina Faso" },
        { id: "BI", text: "Burundi" },
        { id: "KH", text: "Cambodia" },
        { id: "CM", text: "Cameroon" },
        { id: "CA", text: "Canada" },
        { id: "CV", text: "Cape Verde" },
        { id: "KY", text: "Cayman Islands" },
        { id: "CF", text: "Central African Republic" },
        { id: "TD", text: "Chad" },
        { id: "CL", text: "Chile" },
        { id: "CN", text: "China" },
        { id: "CX", text: "Christmas Island" },
        { id: "CC", text: "Cocos (Keeling) Islands" },
        { id: "CO", text: "Colombia" },
        { id: "KM", text: "Comoros" },
        { id: "CG", text: "Congo" },
        { id: "CD", text: "Congo, Democratic Republic" },
        { id: "CK", text: "Cook Islands" },
        { id: "CR", text: "Costa Rica" },
        { id: "CI", text: "Cote D'Ivoire" },
        { id: "HR", text: "Croatia" },
        { id: "CU", text: "Cuba" },
        { id: "CY", text: "Cyprus" },
        { id: "CZ", text: "Czech Republic" },
        { id: "DK", text: "Denmark" },
        { id: "DJ", text: "Djibouti" },
        { id: "DM", text: "Dominica" },
        { id: "DO", text: "Dominican Republic" },
        { id: "EC", text: "Ecuador" },
        { id: "EG", text: "Egypt" },
        { id: "SV", text: "El Salvador" },
        { id: "GQ", text: "Equatorial Guinea" },
        { id: "ER", text: "Eritrea" },
        { id: "EE", text: "Estonia" },
        { id: "ET", text: "Ethiopia" },
        { id: "FK", text: "Falkland Islands (Malvinas)" },
        { id: "FO", text: "Faroe Islands" },
        { id: "FJ", text: "Fiji" },
        { id: "FI", text: "Finland" },
        { id: "FR", text: "France" },
        { id: "GF", text: "French Guiana" },
        { id: "PF", text: "French Polynesia" },
        { id: "TF", text: "French Southern Territories" },
        { id: "GA", text: "Gabon" },
        { id: "GM", text: "Gambia" },
        { id: "GE", text: "Georgia" },
        { id: "DE", text: "Germany" },
        { id: "GH", text: "Ghana" },
        { id: "GI", text: "Gibraltar" },
        { id: "GR", text: "Greece" },
        { id: "GL", text: "Greenland" },
        { id: "GD", text: "Grenada" },
        { id: "GP", text: "Guadeloupe" },
        { id: "GU", text: "Guam" },
        { id: "GT", text: "Guatemala" },
        { id: "GG", text: "Guernsey" },
        { id: "GN", text: "Guinea" },
        { id: "GW", text: "Guinea-Bissau" },
        { id: "GY", text: "Guyana" },
        { id: "HT", text: "Haiti" },
        { id: "HM", text: "Heard Island & Mcdonald Islands" },
        { id: "VA", text: "Holy See (Vatican City State)" },
        { id: "HN", text: "Honduras" },
        { id: "HK", text: "Hong Kong" },
        { id: "HU", text: "Hungary" },
        { id: "IS", text: "Iceland" },
        { id: "IN", text: "India" },
        { id: "ID", text: "Indonesia" },
        { id: "IR", text: "Iran, Islamic Republic Of" },
        { id: "IQ", text: "Iraq" },
        { id: "IE", text: "Ireland" },
        { id: "IM", text: "Isle Of Man" },
        { id: "IL", text: "Israel" },
        { id: "IT", text: "Italy" },
        { id: "JM", text: "Jamaica" },
        { id: "JP", text: "Japan" },
        { id: "JE", text: "Jersey" },
        { id: "JO", text: "Jordan" },
        { id: "KZ", text: "Kazakhstan" },
        { id: "KE", text: "Kenya" },
        { id: "KI", text: "Kiribati" },
        { id: "KR", text: "Korea" },
        { id: "KW", text: "Kuwait" },
        { id: "KG", text: "Kyrgyzstan" },
        { id: "LA", text: "Lao People's Democratic Republic" },
        { id: "LV", text: "Latvia" },
        { id: "LB", text: "Lebanon" },
        { id: "LS", text: "Lesotho" },
        { id: "LR", text: "Liberia" },
        { id: "LY", text: "Libyan Arab Jamahiriya" },
        { id: "LI", text: "Liechtenstein" },
        { id: "LT", text: "Lithuania" },
        { id: "LU", text: "Luxembourg" },
        { id: "MO", text: "Macao" },
        { id: "MK", text: "Macedonia" },
        { id: "MG", text: "Madagascar" },
        { id: "MW", text: "Malawi" },
        { id: "MY", text: "Malaysia" },
        { id: "MV", text: "Maldives" },
        { id: "ML", text: "Mali" },
        { id: "MT", text: "Malta" },
        { id: "MH", text: "Marshall Islands" },
        { id: "MQ", text: "Martinique" },
        { id: "MR", text: "Mauritania" },
        { id: "MU", text: "Mauritius" },
        { id: "YT", text: "Mayotte" },
        { id: "MX", text: "Mexico" },
        { id: "FM", text: "Micronesia, Federated States Of" },
        { id: "MD", text: "Moldova" },
        { id: "MC", text: "Monaco" },
        { id: "MN", text: "Mongolia" },
        { id: "ME", text: "Montenegro" },
        { id: "MS", text: "Montserrat" },
        { id: "MA", text: "Morocco" },
        { id: "MZ", text: "Mozambique" },
        { id: "MM", text: "Myanmar" },
        { id: "NA", text: "Namibia" },
        { id: "NR", text: "Nauru" },
        { id: "NP", text: "Nepal" },
        { id: "NL", text: "Netherlands" },
        { id: "AN", text: "Netherlands Antilles" },
        { id: "NC", text: "New Caledonia" },
        { id: "NZ", text: "New Zealand" },
        { id: "NI", text: "Nicaragua" },
        { id: "NE", text: "Niger" },
        { id: "NG", text: "Nigeria" },
        { id: "NU", text: "Niue" },
        { id: "NF", text: "Norfolk Island" },
        { id: "MP", text: "Northern Mariana Islands" },
        { id: "NO", text: "Norway" },
        { id: "OM", text: "Oman" },
        { id: "PK", text: "Pakistan" },
        { id: "PW", text: "Palau" },
        { id: "PS", text: "Palestinian Territory, Occupied" },
        { id: "PA", text: "Panama" },
        { id: "PG", text: "Papua New Guinea" },
        { id: "PY", text: "Paraguay" },
        { id: "PE", text: "Peru" },
        { id: "PH", text: "Philippines" },
        { id: "PN", text: "Pitcairn" },
        { id: "PL", text: "Poland" },
        { id: "PT", text: "Portugal" },
        { id: "PR", text: "Puerto Rico" },
        { id: "QA", text: "Qatar" },
        { id: "RE", text: "Reunion" },
        { id: "RO", text: "Romania" },
        { id: "RU", text: "Russian Federation" },
        { id: "RW", text: "Rwanda" },
        { id: "BL", text: "Saint Barthelemy" },
        { id: "SH", text: "Saint Helena" },
        { id: "KN", text: "Saint Kitts And Nevis" },
        { id: "LC", text: "Saint Lucia" },
        { id: "MF", text: "Saint Martin" },
        { id: "PM", text: "Saint Pierre And Miquelon" },
        { id: "VC", text: "Saint Vincent And Grenadines" },
        { id: "WS", text: "Samoa" },
        { id: "SM", text: "San Marino" },
        { id: "ST", text: "Sao Tome And Principe" },
        { id: "SA", text: "Saudi Arabia" },
        { id: "SN", text: "Senegal" },
        { id: "RS", text: "Serbia" },
        { id: "SC", text: "Seychelles" },
        { id: "SL", text: "Sierra Leone" },
        { id: "SG", text: "Singapore" },
        { id: "SK", text: "Slovakia" },
        { id: "SI", text: "Slovenia" },
        { id: "SB", text: "Solomon Islands" },
        { id: "SO", text: "Somalia" },
        { id: "ZA", text: "South Africa" },
        { id: "GS", text: "South Georgia And Sandwich Isl." },
        { id: "ES", text: "Spain" },
        { id: "LK", text: "Sri Lanka" },
        { id: "SD", text: "Sudan" },
        { id: "SR", text: "Suriname" },
        { id: "SJ", text: "Svalbard And Jan Mayen" },
        { id: "SZ", text: "Swaziland" },
        { id: "SE", text: "Sweden" },
        { id: "CH", text: "Switzerland" },
        { id: "SY", text: "Syrian Arab Republic" },
        { id: "TW", text: "Taiwan" },
        { id: "TJ", text: "Tajikistan" },
        { id: "TZ", text: "Tanzania" },
        { id: "TH", text: "Thailand" },
        { id: "TL", text: "Timor-Leste" },
        { id: "TG", text: "Togo" },
        { id: "TK", text: "Tokelau" },
        { id: "TO", text: "Tonga" },
        { id: "TT", text: "Trinidad And Tobago" },
        { id: "TN", text: "Tunisia" },
        { id: "TR", text: "Turkey" },
        { id: "TM", text: "Turkmenistan" },
        { id: "TC", text: "Turks And Caicos Islands" },
        { id: "TV", text: "Tuvalu" },
        { id: "UG", text: "Uganda" },
        { id: "UA", text: "Ukraine" },
        { id: "AE", text: "UAE" },
        { id: "GB", text: "United Kingdom" },
        { id: "US", text: "United States" },
        { id: "UM", text: "United States Outlying Islands" },
        { id: "UY", text: "Uruguay" },
        { id: "UZ", text: "Uzbekistan" },
        { id: "VU", text: "Vanuatu" },
        { id: "VE", text: "Venezuela" },
        { id: "VN", text: "Viet Nam" },
        { id: "VG", text: "Virgin Islands, British" },
        { id: "VI", text: "Virgin Islands, U.S." },
        { id: "WF", text: "Wallis And Futuna" },
        { id: "EH", text: "Western Sahara" },
        { id: "YE", text: "Yemen" },
        { id: "ZM", text: "Zambia" },
        { id: "ZW", text: "Zimbabwe" }
    ],
    countryAll: {
        AF: "Afghanistan",
        AX: "Aland Islands",
        AL: "Albania",
        DZ: "Algeria",
        AS: "American Samoa",
        AD: "Andorra",
        AO: "Angola",
        AI: "Anguilla",
        AQ: "Antarctica",
        AG: "Antigua And Barbuda",
        AR: "Argentina",
        AM: "Armenia",
        AW: "Aruba",
        AU: "Australia",
        AT: "Austria",
        AZ: "Azerbaijan",
        BS: "Bahamas",
        BH: "Bahrain",
        BD: "Bangladesh",
        BB: "Barbados",
        BY: "Belarus",
        BE: "Belgium",
        BZ: "Belize",
        BJ: "Benin",
        BM: "Bermuda",
        BT: "Bhutan",
        BO: "Bolivia",
        BA: "Bosnia And Herzegovina",
        BW: "Botswana",
        BV: "Bouvet Island",
        BR: "Brazil",
        IO: "British Indian Ocean Territory",
        BN: "Brunei Darussalam",
        BG: "Bulgaria",
        BF: "Burkina Faso",
        BI: "Burundi",
        KH: "Cambodia",
        CM: "Cameroon",
        CA: "Canada",
        CV: "Cape Verde",
        KY: "Cayman Islands",
        CF: "Central African Republic",
        TD: "Chad",
        CL: "Chile",
        CN: "China",
        CX: "Christmas Island",
        CC: "Cocos (Keeling) Islands",
        CO: "Colombia",
        KM: "Comoros",
        CG: "Congo",
        CD: "Congo, Democratic Republic",
        CK: "Cook Islands",
        CR: "Costa Rica",
        CI: "Cote D'Ivoire",
        HR: "Croatia",
        CU: "Cuba",
        CY: "Cyprus",
        CZ: "Czech Republic",
        DK: "Denmark",
        DJ: "Djibouti",
        DM: "Dominica",
        DO: "Dominican Republic",
        EC: "Ecuador",
        EG: "Egypt",
        SV: "El Salvador",
        GQ: "Equatorial Guinea",
        ER: "Eritrea",
        EE: "Estonia",
        ET: "Ethiopia",
        FK: "Falkland Islands (Malvinas)",
        FO: "Faroe Islands",
        FJ: "Fiji",
        FI: "Finland",
        FR: "France",
        GF: "French Guiana",
        PF: "French Polynesia",
        TF: "French Southern Territories",
        GA: "Gabon",
        GM: "Gambia",
        GE: "Georgia",
        DE: "Germany",
        GH: "Ghana",
        GI: "Gibraltar",
        GR: "Greece",
        GL: "Greenland",
        GD: "Grenada",
        GP: "Guadeloupe",
        GU: "Guam",
        GT: "Guatemala",
        GG: "Guernsey",
        GN: "Guinea",
        GW: "Guinea-Bissau",
        GY: "Guyana",
        HT: "Haiti",
        HM: "Heard Island & Mcdonald Islands",
        VA: "Holy See (Vatican City State)",
        HN: "Honduras",
        HK: "Hong Kong",
        HU: "Hungary",
        IS: "Iceland",
        IN: "India",
        ID: "Indonesia",
        IR: "Iran, Islamic Republic Of",
        IQ: "Iraq",
        IE: "Ireland",
        IM: "Isle Of Man",
        IL: "Israel",
        IT: "Italy",
        JM: "Jamaica",
        JP: "Japan",
        JE: "Jersey",
        JO: "Jordan",
        KZ: "Kazakhstan",
        KE: "Kenya",
        KI: "Kiribati",
        KR: "Korea",
        KW: "Kuwait",
        KG: "Kyrgyzstan",
        LA: "Lao People's Democratic Republic",
        LV: "Latvia",
        LB: "Lebanon",
        LS: "Lesotho",
        LR: "Liberia",
        LY: "Libyan Arab Jamahiriya",
        LI: "Liechtenstein",
        LT: "Lithuania",
        LU: "Luxembourg",
        MO: "Macao",
        MK: "Macedonia",
        MG: "Madagascar",
        MW: "Malawi",
        MY: "Malaysia",
        MV: "Maldives",
        ML: "Mali",
        MT: "Malta",
        MH: "Marshall Islands",
        MQ: "Martinique",
        MR: "Mauritania",
        MU: "Mauritius",
        YT: "Mayotte",
        MX: "Mexico",
        FM: "Micronesia, Federated States Of",
        MD: "Moldova",
        MC: "Monaco",
        MN: "Mongolia",
        ME: "Montenegro",
        MS: "Montserrat",
        MA: "Morocco",
        MZ: "Mozambique",
        MM: "Myanmar",
        NA: "Namibia",
        NR: "Nauru",
        NP: "Nepal",
        NL: "Netherlands",
        AN: "Netherlands Antilles",
        NC: "New Caledonia",
        NZ: "New Zealand",
        NI: "Nicaragua",
        NE: "Niger",
        NG: "Nigeria",
        NU: "Niue",
        NF: "Norfolk Island",
        MP: "Northern Mariana Islands",
        NO: "Norway",
        OM: "Oman",
        PK: "Pakistan",
        PW: "Palau",
        PS: "Palestinian Territory, Occupied",
        PA: "Panama",
        PG: "Papua New Guinea",
        PY: "Paraguay",
        PE: "Peru",
        PH: "Philippines",
        PN: "Pitcairn",
        PL: "Poland",
        PT: "Portugal",
        PR: "Puerto Rico",
        QA: "Qatar",
        RE: "Reunion",
        RO: "Romania",
        RU: "Russian Federation",
        RW: "Rwanda",
        BL: "Saint Barthelemy",
        SH: "Saint Helena",
        KN: "Saint Kitts And Nevis",
        LC: "Saint Lucia",
        MF: "Saint Martin",
        PM: "Saint Pierre And Miquelon",
        VC: "Saint Vincent And Grenadines",
        WS: "Samoa",
        SM: "San Marino",
        ST: "Sao Tome And Principe",
        SA: "Saudi Arabia",
        SN: "Senegal",
        RS: "Serbia",
        SC: "Seychelles",
        SL: "Sierra Leone",
        SG: "Singapore",
        SK: "Slovakia",
        SI: "Slovenia",
        SB: "Solomon Islands",
        SO: "Somalia",
        ZA: "South Africa",
        GS: "South Georgia And Sandwich Isl.",
        ES: "Spain",
        LK: "Sri Lanka",
        SD: "Sudan",
        SR: "Suriname",
        SJ: "Svalbard And Jan Mayen",
        SZ: "Swaziland",
        SE: "Sweden",
        CH: "Switzerland",
        SY: "Syrian Arab Republic",
        TW: "Taiwan",
        TJ: "Tajikistan",
        TZ: "Tanzania",
        TH: "Thailand",
        TL: "Timor-Leste",
        TG: "Togo",
        TK: "Tokelau",
        TO: "Tonga",
        TT: "Trinidad And Tobago",
        TN: "Tunisia",
        TR: "Turkey",
        TM: "Turkmenistan",
        TC: "Turks And Caicos Islands",
        TV: "Tuvalu",
        UG: "Uganda",
        UA: "Ukraine",
        AE: "UAE",
        GB: "United Kingdom",
        US: "United States",
        UM: "United States Outlying Islands",
        UY: "Uruguay",
        UZ: "Uzbekistan",
        VU: "Vanuatu",
        VE: "Venezuela",
        VN: "Viet Nam",
        VG: "Virgin Islands, British",
        VI: "Virgin Islands, U.S.",
        WF: "Wallis And Futuna",
        EH: "Western Sahara",
        YE: "Yemen",
        ZM: "Zambia",
        ZW: "Zimbabwe"
      }
}

export default state